database.url = "jdbc:postgresql://devdb.zivver.org:5432/zivver_mathias?stringtype=unspecified&useUnicode=yes&characterEncoding=UTF-8"
webapp.url = "http://localhost:3000"
webapp.apiUrl = "http://localhost:18080"
jwt.secret = "randomstring"
messagebird.apiKey = "test_zEAo81giumPS5Duys0ZRVQLHd"
mail.host = localhost
mail.port = 1025
mail.tls = false
mail.auth = false
